/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 gcpd_g.gltf --transform 
Files: gcpd_g.gltf [199.04KB] > gcpd_g-transformed.glb [25.11KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gtpd(props) {
  const { nodes, materials } = useGLTF('/models/gtpd_compressed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.left_half.geometry} material={materials.PaletteMaterial001} position={[0, 0.048, 0.009]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.052, 0.13, 0.022]} />
    </group>
  )
}

useGLTF.preload('/models/gtpd_compressed.glb')
