/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 wreck_g.gltf --transform 
Files: wreck_g.gltf [237.22KB] > wreck_g-transformed.glb [26.92KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Wreck(props) {
  const { nodes, materials } = useGLTF('/models/wreck_compressed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.PaletteMaterial004} />
      </group>
      <instancedMesh args={[nodes.Mesh001.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Mesh001.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh001_1.geometry, materials.PaletteMaterial004, 5]} instanceMatrix={nodes.Mesh001_1.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh001_2.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Mesh001_2.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh001_3.geometry, materials.PaletteMaterial002, 5]} instanceMatrix={nodes.Mesh001_3.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/wreck_compressed.glb')
